name: Daily sanity main
# Uses solace/solace-pubsub-standard:edge image

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    name: Daily test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup test broker
        run: |
          mkdir -p $HOME/solace; chmod 777 $HOME/solace
          docker run -d -p 8080:8080 -p 55555:55555 --shm-size=1g --env username_admin_globalaccesslevel=admin --env username_admin_password=admin --env system_scaling_maxkafkabridgecount="10" --name=solace \
            --mount type=bind,source=$HOME/solace,destination=/var/lib/solace,ro=false solace/solace-pubsub-standard:edge
          while ! curl -s localhost:8080 | grep aurelia ; do sleep 1 ; done

      - name: Set up Terraform latest - public
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: true

      - name: Run provider test - create custom messageVPN with large config
        run: |
          pushd ci/broker_vpn_test
          terraform init
          $(find .terraform/ | grep terraform-provider) version
          # Create
          terraform plan
          terraform apply -auto-approve
          sleep 1
          popd

      - name: Run generate test - generate complete large config file for custom messageVPN file
        run: |
          pushd ci/broker_vpn_test
          SOLACEBROKER_USERNAME=admin SOLACEBROKER_PASSWORD=admin $(find .terraform/ | grep terraform-provider) generate --url=http://localhost:8080 solacebroker_msg_vpn.test test messageVpn.tf
          cat messageVpn.tf
          rm messageVpn.tf
          popd

      - name: Run provider test - delete large config
        run: |
          pushd ci/broker_vpn_test
          terraform plan
          terraform destroy -auto-approve
          sleep 1
          popd
