name: Update licenses

on:
  pull_request:
    branches:
      - 'v[0-9]*[.][0-9]*[.][0-9]{0,3}'

jobs:
  build:
    name: Build & test Terraform provider
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      # - name: Generate documentations
      #   run: |
      #     make generate-docs

      - name: Build provider
        run: |
          go mod tidy
          go fmt
          go install .
          ~/go/bin/terraform-provider-solacebroker version
          ~/go/bin/terraform-provider-solacebroker help

      # - name: Generate third party licenses list
      #   run: |
      #     make generate-license

      - name: Prep product release for Whitesource
        run: |
          VERSION=$(cat version.go | grep version | awk -F '"' '{print $2}')
          sed -i "s/productVersion=.*$/productVersion=v${VERSION}/g" ci/whitesource/whitesource-agent.config
          cat ci/whitesource/whitesource-agent.config | grep productVersion

      - name: Run Whitesource Action to update licenses
        uses: SolaceDev/Mend-Scan-GHA@v1.0.0
        with:
          wssURL: https://saas.whitesourcesoftware.com/agent
          apiKey: ${{ secrets.WSS_API_KEY }}
          productName: 'terraform-provider-solacebroker'
          projectName: 'terraform-provider-solacebroker'
          configFile: 'ci/whitesource/whitesource-agent.config'
